---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: webapp
  spec:
    replicas: 2
    selector:
      matchLabels:
          app: webapp
    template: 
      metadata:
        labels:
          app: webapp
      spec:
        containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0
...
